# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 06da640b64f6147b6b7c7f6782766ce6293bf1154082d7ae7c29f6d1e991cebf02afad160d63925e81b58c513214ceb40c61dbc9de55d59054a89ae306da625a

test:
  secret_key_base: 8651d6acf010a5d8d04986d8e76940a12d15872914fcf76c5fa835d658dff2504ce711e3c2ecd1b3d606e9b9b04762a25b3a189697c645428cb352c34244e61c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
